### ISSUE TITLE
Search returns odd line in some logs

### ISSUE THREAD

**Issue by CaitlynMainer** [CaitlynMainer/OCLogs#1]
https://oclogs.pc-logix.com/search?search=Meh
File is: 2014-05-15.log
http://michi.pc-logix.com/chrome_2017-01-31_19-34-14.png
The above doesn't contain the line "Meh" in the line by me, and when click on the line number (751)
https://oclogs.pc-logix.com/parser.php?log=2014-05-15.log#L751 you'll notice the line it printed on the search page is actually line 572, but neither 571 or 572 has the word "Meh" in it.

**Comment by Forecaster** [comment]
Oh, that's because it starts at 0, but the lines start at one. I'll just add an offset for that. But the match is strange.

**Comment by Forecaster** [comment]
The line **does** have "meh" in it xD

"...and it still so[meh]ow feels..."

**Comment by Forecaster** [comment]
I'll look into highlighting the match in each line. It will probably involve regex

**Comment by CaitlynMainer** [comment]
Doh...
